# Generated by Django 3.1.2 on 2020-10-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_TBL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='NAME')),
                ('pnumber', models.CharField(max_length=50, verbose_name='NUMBER')),
                ('email', models.CharField(max_length=50, verbose_name='EMAIL')),
                ('status', models.CharField(max_length=50, verbose_name='STATUS')),
                ('hospital_dt', models.DateTimeField(verbose_name='HOSPITALIZATION_DATE')),
                ('leave_hospital_dt', models.DateTimeField(verbose_name='LEAVING_HOSPITALIZATION_DATE')),
                ('address', models.CharField(max_length=50, verbose_name='ADDRESS')),
            ],
            options={
                'ordering': ('hospital_dt', 'name', 'status', 'leave_hospital_dt'),
            },
        ),
    ]
