# Generated by Django 3.1.2 on 2020-10-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient_tbl',
            options={'ordering': ('id', 'hospital_dt', 'name', 'status')},
        ),
        migrations.RemoveField(
            model_name='patient_tbl',
            name='leave_hospital_dt',
        ),
    ]
